apiVersion: v1
kind: Secret
metadata:
  name: predictora-backend-secrets
  namespace: predictora-dev
type: Opaque
stringData:
  JWT_SECRET_KEY: "e8a84ee18cb48c56e91d4028cb1ca62806d971a434d7cc6c3de10f259dbea6bf312f0e6ef205f97604c19a226617d6b48c2991a644ae554ebc4e9200a7b8dec5"
  ADMIN_USERNAME: "admin-dev@predictora.ai"
  ADMIN_PASSWORD: "DevAdmin123!"
  PREDICTORA_API_KEY: "PREDICTORA_DEV_KEY_123"
