apiVersion: v1
kind: Secret
metadata:
  name: predictora-backend-secrets
  namespace: predictoraai
type: Opaque
stringData:
  JWT_SECRET_KEY: "ab439cb0a650522dba43b27616890cec2524edba582c779bc24d6eefbe24fec24541bef0c00d7ad71ffc972bb18d5d48fc815becbfa0d82fa3ff594eb3651b2b"
  PREDICTORA_API_KEY: "PREDICTORA_KEY_123"
  ADMIN_USERNAME: "admin@predictora.ai"
  ADMIN_PASSWORD: "PredictoraAdmin123!"
